[theme]
base = "light"
primaryColor = "#087F8C"
backgroundColor = "#F7F9FC"
secondaryBackgroundColor = "#EDF1F7"
textColor = "#182B49"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
